name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: minicli/action-contributors@v3
      name: "Update a projects CONTRIBUTORS file"
      env:
        CONTRIB_REPOSITORY: 'martinwoodward/dotnetweb'
        CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
    - name: Commit changes
      uses: test-room-7/action-update-file@v1
      with:
        file-path: 'CONTRIBUTORS.md'
        commit-msg: Update Contributors
        github-token: ${{ secrets.GITHUB_TOKEN }}
